# Generated by Django 4.0.5 on 2022-07-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redisapp', '0002_schoolitem_remove_employeedetail_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolItem',
        ),
    ]
