# Generated by Django 4.0.5 on 2022-07-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redisapp', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolItem',
        ),
    ]
